# -*- coding: utf-8 -*-
"""Copy_of_NUZ_TO_YLM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16pmJw_XE_qJ-2QgBT52bkNa8yR1J7Ff5
"""

import folium
from branca.element import Figure

path1=[[16.784888313189743, 80.84660345617763],[16.74105083842801, 80.89861288069633],[16.727085836055263, 80.91064283157631],[16.708119581078204, 80.9252830188909],
       [16.678072381848303, 80.95056607797736],[16.685501065377615, 80.9832638247181],[16.6875,81.0058],[16.711389733176375, 81.02507056218167],[16.76813007964905, 81.21081814161424]
       ,[16.782667198316805, 81.22569774088448],[16.79778462178353, 81.22843072862948],[16.830341136677795, 81.25029463354574],[16.865798116275627, 81.30373972768756]
       ,[16.914322702789836, 81.35505916190533],[17.04105257173189, 81.6139232306011],[17.046568815303143, 81.84136854782354],
       [16.816699897256026, 82.16696563094204]]

path2=[[16.784888313189743, 80.84660345617763],[16.74105083842801, 80.89861288069633],[16.727085836055263, 80.91064283157631],[16.708119581078204, 80.9252830188909],
       [16.678072381848303, 80.95056607797736],[16.654559345610387, 80.99764416980719],[16.66935623064159, 81.01337825747034],[16.711389733176375, 81.02507056218167],[16.76813007964905, 81.21081814161424]
       ,[16.782667198316805, 81.22569774088448],[16.79778462178353, 81.22843072862948],[16.830341136677795, 81.25029463354574],[16.865798116275627, 81.30373972768756]
       ,[16.914322702789836, 81.35505916190533],[17.04105257173189, 81.6139232306011],[17.046568815303143, 81.84136854782354],
       [16.816699897256026, 82.16696563094204]]

path3=[[16.784888313189743, 80.84660345617763],[16.74105083842801, 80.89861288069633],[16.727085836055263, 80.91064283157631],[16.708119581078204, 80.9252830188909],
       [16.678072381848303, 80.95056607797736],[16.654559345610387, 80.99764416980719],[16.66935623064159, 81.01337825747034],[16.711389733176375, 81.02507056218167],[16.7107,81.0952],
       [16.830341136677795, 81.25029463354574],[16.865798116275627, 81.30373972768756]
       ,[16.914322702789836, 81.35505916190533],[17.04105257173189, 81.6139232306011],[16.816699897256026, 82.16696563094204]]
path4=[[16.784888313189743, 80.84660345617763],[16.74105083842801, 80.89861288069633],[16.727085836055263, 80.91064283157631],[16.708119581078204, 80.9252830188909],
       [16.678072381848303, 80.95056607797736],[16.654559345610387, 80.99764416980719],[16.66935623064159, 81.01337825747034],[16.711389733176375, 81.02507056218167],[16.7107,81.0952]
       ,[17.00911862555443, 81.80554970624247],[17.08352923205807, 81.901112909183],[17.085100233729467, 82.0732377213678],[17.0050912368856, 82.23794680295217],
       [16.816699897256026, 82.16696563094204]
       ]

fig=Figure(height=1000,width=1500)
map5=folium.Map(location=[17.046568815303143, 81.84136854782354],tiles='cartodbpositron',zoom_start=14)
fig.add_child(map5)
f1=folium.FeatureGroup("ROUTE 1")
f2=folium.FeatureGroup("ROUTE 2")
f3=folium.FeatureGroup("ROUTE 3")
f4=folium.FeatureGroup("ROUTE 4")
line_1=folium.vector_layers.PolyLine(path1,popup='<b>R-1</b>',tooltip='Vehicle_1',color='blue',weight=10).add_to(f1)
line_2=folium.vector_layers.PolyLine(path2,popup='<b>R-2</b>',tooltip='Vehicle_2',color='green',weight=10).add_to(f2)
line_3=folium.vector_layers.PolyLine(path3,popup='<b>R-3</b>',tooltip='Vehicle_3',color='red',weight=10).add_to(f3)
line_4=folium.vector_layers.PolyLine(path4,popup='<b>R-4</b>',tooltip='Vehicle_4',color='yellow',weight=10).add_to(f4)
f1.add_to(map5)
f2.add_to(map5)
f3.add_to(map5)
f4.add_to(map5)
folium.Marker(location=[16.9891, 82.2475],tooltip='KAKINADA_BEACH',icon=folium.Icon(color='red',prefix="fa",icon='anchor')).add_to(map5)
folium.Marker(location=[16.6356, 80.9716],tooltip='HJN HANUMA',icon=folium.Icon(color='green',icon_color="white",prefix="fa",icon="bell")).add_to(map5)
folium.Marker(location=[16.7107, 81.0952],tooltip='ELURU',icon=folium.Icon(color='green',icon='cloud')).add_to(map5)
folium.Marker(location=[17.0005,81.8040],tooltip='RAJAMUNDRY AIRPORT',icon=folium.Icon(color='pink',prefix="fa",icon='plane')).add_to(map5)
folium.Marker(location=[16.784888313189743, 80.84660345617763],tooltip='NUZVID',icon=folium.Icon(color='yellow',prefix="fa",icon="cab")).add_to(map5)
folium.Marker(location=[16.820406635512484, 82.16440160629737],tooltip='CHEDUVADA',icon=folium.Icon(color='black',icon='home')).add_to(map5)
folium.Marker(location=[16.7272, 82.2176],tooltip='YANAM',icon=folium.Icon(color='blue',icon='home')).add_to(map5)
folium.Marker(location=[16.8100, 82.2393],tooltip='KORINGA WILD LIFE SANCTURY',icon=folium.Icon(color='green',icon='star')).add_to(map5)
folium.Marker(location=[16.7856, 80.8487],tooltip='HOTEL MAHATHI',icon=folium.Icon(color='green',prefix="fa",icon='hotel')).add_to(map5)
folium.Marker(location=[17.0675,81.8844],tooltip='GSL RJY',icon=folium.Icon(color='green',prefix="fa",icon='ambulance')).add_to(map5)
map5

